### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by Phos69** [microBeesTech/pythonSDK#1]
Hello,
I have 8 microbees plugs, 4 lighbees and a thermobee.
I assumed this would work with any other custom integration in Home Assistant, so I imported it
Nothing worked, so I checked and the __init__.py file seems empty, and the other files look auto-generated.

I am willing to participate in development and testing of to integrate microbees devices into Home Assistant

**Comment by FedDam** [comment]
Hello, a new version has been released
